### ISSUE TITLE
Tag release commits

### ISSUE THREAD

**Issue by patcon** [ncerny/chef-cookbook#12]
Hey there! Great repo. Thanks for all the work :)

I'd like to request that in the future and perhaps for past commits. This would help people who try to stick to stable(ish) tags, or at least who don't want the repo floating with HEAD during berkshelf updates :)

Much appreciated!

**Comment by ncerny** [comment]
This is a great callout.  We've not gone through much "release" rigamarole because we haven't technically "released" it (it's still pre-1.0).  We can totally start tagging though, that's completely fair.

**Comment by patcon** [comment]
Actually, I'll leave open until tags happen, just for the naggingness of incomplete ticketness

**Comment by ncerny** [comment]
I'm going to close this issue.  We've begun to tag on releases.
